platform :ios, '8.0'

use_frameworks!

target “Survata Says” do
	pod 'Survata', :git => 'git@github.com:Survata/survata-ios-public-sdk.git'
    pod 'Greycats', :git => 'git@github.com:greycats/Greycats.swift.git'
    pod 'SVProgressHUD'
	pod 'HockeySDK', '~> 3.8.5'
end
